app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Haven VPN
publisher_url: https://haven.yagihub.ru
display_name: Haven
create_desktop_icon: true
install_dir_name: "{autopf64}\\Haven"
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
  - ru
script_template: inno_setup.sas
